site_name: Horde SDK Documentation

plugins:
- search
- mermaid2:
    version: '10.1.0'
    arguments:
        theme: 'dark'
        themeVariables:
            darkMode: true
            fontSize: 24
            primaryColor: '#ff0000'

- awesome-pages
- autorefs
- mkdocstrings:
    handlers:
      python:
        options:
          members_order: source
          docstring_section_style: list
          show_if_no_docstring: true
          separate_signature: true
          show_signature_annotations: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom

theme:
  name: material
  language: en
  palette:
    scheme: slate

extra_css:
  - stylesheets/extra.css
