name: Tests

on:
  push:
    branches:
      - main
    paths:
      - '**.py'
      - '**.json'
      - 'tox.ini'
      - '.github/workflows/maintests.yml'
      - '.github/workflows/prtests.yml'
      - '.github/workflows/release.yml'
      - '.pre-commit-config.yaml'
      - 'requirements.txt'
      - 'requirements.dev.txt'
      - 'requirements.docs.txt'
jobs:
  build:
    env:
      AIWORKER_CACHE_HOME: ${{ github.workspace }}/.cache
      TESTS_ONGOING: 1
      HORDE_SDK_TESTING: 1
      HORDE_MODEL_REFERENCE_MAKE_FOLDERS: 1
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install tox and any other packages
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade -r requirements.dev.txt
      - name: Run unit tests
        run: tox -e tests-no-api-calls
