name: Tests

on:
  push:
    branches:
      - main
    paths:
      - '**.py'
      - '**.json'
      - 'tox.ini'
      - '.github/workflows/maintests.yml'
      - '.github/workflows/prtests.yml'
      - '.github/workflows/release.yml'
      - '.pre-commit-config.yaml'
      - 'requirements.txt'
      - 'requirements.dev.txt'
      - 'requirements.docs.txt'
jobs:
  build:
    env:
      AIWORKER_CACHE_HOME: ${{ github.workspace }}/.cache
      TESTS_ONGOING: "1"
      AI_HORDE_TESTING: "1"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.12"
          - "3.13"

    steps:
      - uses: actions/checkout@v4
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - name: Install the project
        run: uv sync --locked --all-extras --dev


      - name: Run tests
        run: uv run pytest tests --ignore-glob='**/*api_calls*' -m "not api_side_ci"